### ISSUE TITLE
Add support for vim.uv

### ISSUE THREAD

**Issue by ndavd** [ii14/emmylua-nvim#14]
https://neovim.io/doc/user/lua.html#vim.uv

**Comment by ii14** [comment]
Neovim now provides annotations, so this repository is pretty much obsolete now.

Can you check if this library configuration for lua language server works for you?
```lua
workspace = {
  library = {
    vim.env.VIMRUNTIME,
    '${3rd}/luv/library',
  },
}
```

**Comment by ndavd** [comment]
Oh that works, yes. Thanks! Closing this
