### ISSUE TITLE
Add metamethods for `vim.opt` and `vim.opt_local`

### ISSUE THREAD

**Issue by akinsho** [ii14/emmylua-nvim#2]
When using the metamethods like `get`, `append` prepend for `vim.opt` and `vim.opt_local` the typing complains that these methods do not exist. Ideally, this package can include a `@class` annotation for these methods which includes the typing for these methods.

**Comment by ii14** [comment]
They already are annotated:

![screenshot-220728-123734](https://user-images.githubusercontent.com/59243201/181486117-c4884f03-bb16-47dd-899d-11d183627942.png)

What is the code you get the warning on?

**Comment by akinsho** [comment]
I get it on spell lang
<img width="818" alt="image" src="https://user-images.githubusercontent.com/22454918/181491964-7121e556-1ed9-4308-a7de-91b5b6c05b66.png">

and format options
<img width="390" alt="image" src="https://user-images.githubusercontent.com/22454918/181492018-20be0166-60db-4a03-b52a-3f3e705153c3.png">
just tried your example and each option comes back as an `enum` so doesn't have the method attached.
I'm using
```lua
  sumneko_lua = function()
    local path = vim.split(package.path, ';')
    table.insert(path, 'lua/?.lua')
    table.insert(path, 'lua/?/init.lua')

    local lib = vim.tbl_filter(function(dir)
      if dir:match('emmy') then return true end
      return not vim.startswith(dir, fn.stdpath('data') .. '/site/') -- ignore mountain of plugins
    end, api.nvim_get_runtime_file('', true))

    return {
      settings = {
        Lua = {
          runtime = {
            path = path,
            version = 'LuaJIT',
          },
          format = { enable = false },
          diagnostics = {
            globals = { 'vim', 'describe', 'it', 'before_each', 'after_each', 'packer_plugins' },
          },
          completion = { keywordSnippet = 'Replace', callSnippet = 'Replace' },
          workspace = {
            library = lib,
          },
          telemetry = {
            enable = false,
          },
        },
      },
    }
```
