### ISSUE TITLE
Mark optional arguments as optional

### ISSUE THREAD

**Issue by akinsho** [ii14/emmylua-nvim#4]
Hi (again 😅)

Sumneko's new versions (at some point) started checking that arguments were all provided to a function, unless they were marked as optional they would show as missing. A lot of vim.* helpers have optional arguments, so a lot of these functions show up with errors. The one that comes to mind for me the most is `vim.list_extend` but that's just what I've noticed the most.

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/22454918/182551200-fd9a8844-be39-4a44-b939-1e0538a975bf.png">

**Comment by ii14** [comment]
Annotations for these functions are copied verbatim from `shared.lua` and `_editor.lua`. Unfortunately this is something that has to be fixed in neovim.

**Comment by akinsho** [comment]
Ah, that makes sense, thanks for clarifying. Tbh I haven't been able to discern if the nvim team are strictly using emmy lua annotations or not as it seems sporadic, some annotations are correct and others sometimes reference undeclared types. A common one is `Optional` or `Callback` anyway, I'll close this here since the issue isn't with this plugin

**Comment by ii14** [comment]
I believe it's mostly in the older code. Also docs are generated from annotations, and in some cases I believe the parser would have to be adjusted to handle some types.
