### ISSUE TITLE
any plan to add annotations for vim.treesitter?

### ISSUE THREAD

**Issue by haolian9** [ii14/emmylua-nvim#7]
annotations for these userdata (tsnode, query, languagetree, tstree) would help a lot when writing treesitter relevant code.
though i failed to find a programmatically way to generate annotations for `vim.treesitter.*`, i added [some of them](#) manually.

**Comment by ii14** [comment]
Generating it automatically seems tough. I don't pay too much attention to treesitter, so I don't have any plans for it. But if anyone wants to manually add annotations and keep them in sync then I can include it.

**Comment by haolian9** [comment]
thanks for replying!
i got some ideas from [gen_vimdoc.py](https://github.com/neovim/neovim/blob/master/scripts/gen_vimdoc.py#L232), and   `nvim/runtime/lua/vim/{treesitter/*.lua,treesitter.lua}` are well annotated.

... some minutes later ...

so we dont need to provide annotations of these lua objects for sumneko/lua-language-server.
with above simplification, only `userdata tsnode` needs annotations, then i think this issue is not a problem, i just need to  add these lua files to the langserver's config. haha, that's great.
